apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: myapp
  namespace: dev
spec:
  containers:
  - name: myapp
    image: nginx
    env:
    - name: using env confimap
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: Name
    - name: using env confimap
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: FirstName

    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
      requests:
        memory: "64Mi"
        cpu: "100m"
    ports:
    - containerPort: 8080
