apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: myapp
  namespace: dev
spec:
  containers:
  - name: myapp
    image: nginx
    envFrom:
    - configMapRef:
        name: myconfigmap
    - secretRef:
        name: mysecret
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
      requests:
        memory: "64Mi"
        cpu: "100m"
    ports:
    - containerPort: 8080


